services:
  chartapp:
    build: .
    container_name: Dockerized_chartapp
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads   # persist uploaded files
      - ./templates:/app/templates  # persist templates